github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/utilities-maintainers"

package:
  repositories:   ["docker.io/paketobuildpacks/health-checker"]
  register:       true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
- registry: docker.io
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- name:            Tiny Health Checker
  id:              thc
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       ^tiny-health-checker-x86_64-unknown-linux-musl\.tar\.xz$
    owner:      dmikusa
    repository: tiny-health-checker
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

# ARM64
- name:            Tiny Health Checker ARM64
  id:              thc
  uses:            docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       ^tiny-health-checker-aarch64-unknown-linux-musl\.tar\.xz$
    owner:      dmikusa
    repository: tiny-health-checker
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    arch:       arm64
