# Copyright 2018-2024 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that provides a health check binary tool"
  homepage = "https://github.com/paketo-buildpacks/health-checker"
  id = "paketo-buildpacks/health-checker"
  keywords = ["health", "check", "monitor"]
  name = "Paketo Buildpack for Health Checkers"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/health-checker/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/main", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/main"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    default = "false"
    description = "contributes a health checker if enabled"
    name = "BP_HEALTH_CHECKER_ENABLED"

  [[metadata.configurations]]
    build = true
    default = "thc"
    description = "which health checker to contribute"
    name = "BP_HEALTH_CHECKER_DEPENDENCY"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:dmikusa-pivotal:tiny-health-checker:0.28.0:*:*:*:*:*:*:*"]
    id = "thc"
    name = "Tiny Health Checker"
    purl = "pkg:generic/thc@0.28.0?arch=amd64"
    sha256 = "45f8de030d4e0fe3b8a4b6ccc5ffcd02a2aeb435970d8ff037f3c0631c11c1bb"
    source = "https://github.com/dmikusa/tiny-health-checker/archive/refs/tags/v0.28.0.tar.gz"
    source-sha256 = "a118fd1a4030c3e90adbcfab6048a44fb807256d294f86215dce18eda9a2285c"
    stacks = ["*"]
    uri = "https://github.com/dmikusa/tiny-health-checker/releases/download/v0.28.0/thc-x86_64-unknown-linux-musl"
    version = "0.28.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2"
      uri = "https://github.com/dmikusa-pivotal/tiny-health-checker/blob/main/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:dmikusa-pivotal:tiny-health-checker:0.27.0:*:*:*:*:*:*:*"]
    id = "thc"
    name = "Tiny Health Checker"
    purl = "pkg:generic/thc@0.27.0?arch=arm64"
    sha256 = "cfbf5c7d4258ed72d343ae9f7319ad509b69f57065fad4d1308e247bff777287"
    source = "https://github.com/dmikusa/tiny-health-checker/archive/refs/tags/v0.27.0.tar.gz"
    source-sha256 = "e364e09c1c67330154463ff15c2408fad6ec1c0ed02cea3815223af1a33b93e2"
    stacks = ["*"]
    uri = "https://github.com/dmikusa/tiny-health-checker/releases/download/v0.27.0/thc-aarch64-unknown-linux-musl"
    version = "0.27.0"

    [[metadata.dependencies.licenses]]
      type = "Apache-2"
      uri = "https://github.com/dmikusa-pivotal/tiny-health-checker/blob/main/LICENSE"

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
